changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Layout and Design 🎨
      labels:
        - layout
    - title: Exciting New Features 🎉
      labels:
        - feature
        - enhancement
    - title: Bug fixes 🐛
      labels:
        - bugfix
        - patch
    - title: Other Changes
      labels:
        - "*"
