name: "Notify release to Slack"
on:
  release:
    types: [published]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Slack Markdown Converter
        uses: LoveToKnow/slackify-markdown-action@v1.0.2
        id: slackify
        with:
          text: ${{ github.event.release.body }}
      - uses: actions/checkout@v2
      - run: |
          echo "${{ github.event.release.tag_name }}"
          echo "${{ github.event.release.name }}"
          echo "${{ github.event.release.body }}"
      - name: Notify release to Slack
        uses: lizefield/notify-release-to-slack@v1.0
        with:
          slackWebhookUrl: ${{ secrets.SLACK_NOTIFICATIONS_WEBHOOK }}
          releaseMessage: ${{ steps.slackify.outputs.text }}
          #releaseMessage: ${{ github.event.release.body }}
